spring:
  application:
    name: allin
  datasource:
    url: jdbc:postgresql://localhost:54321/allin
    username: bertrand
    password: A1b2C3d4E5f6G7h8I9j0
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration, classpath:db/dev/migration


